CREATE TABLE "listings" (
	"funda_id" text PRIMARY KEY NOT NULL,
	"url" text NOT NULL,
	"address" text NOT NULL,
	"postcode" text,
	"neighbourhood" text,
	"price" integer NOT NULL,
	"bedrooms" integer NOT NULL,
	"living_area" integer NOT NULL,
	"energy_label" text,
	"object_type" text,
	"construction_year" integer,
	"description" text,
	"has_garden" boolean,
	"has_balcony" boolean,
	"has_roof_terrace" boolean,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"photos" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" text DEFAULT 'Beschikbaar' NOT NULL,
	"offered_since" text,
	"disappeared_at" timestamp with time zone,
	"route_fareharbor" jsonb,
	"route_airwallex" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
